import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';

const thresholds = { 1: 0, 2: 200, 3: 224 };

export default function DashboardPage() {
  const { user, logout } = useAuth();
  const [data, setData] = useState(null); const [scenarios, setScenarios] = useState([]); const [error, setError] = useState('');
  useEffect(() => {
    Promise.all([api.progress(), api.scenarios()]).then(([progress, scenarioData]) => {
      setData(progress); setScenarios(scenarioData.scenarios);
    }).catch(err => setError(err.message));
  }, []);

  if (user.role === 'FACULTY') return <FacultyPlaceholder />;
  const p = data?.progress;
  return <main className="app-shell">
    <header className="topbar"><div className="brand">TRIAGE<span>LEARN</span></div><button className="secondary" onClick={logout}>Log out</button></header>
    <section className="hero"><div><p className="eyebrow">STUDENT DASHBOARD</p><h1>Welcome, {user.full_name.split(' ')[0]} 👋</h1><p className="muted">Build your clinical reasoning through structured ESI triage practice.</p></div></section>
    {error && <div className="alert error">{error}</div>}
    <section className="stats">
      <Stat label="Total XP" value={p?.total_xp ?? 0} />
      <Stat label="Current tier" value={`Tier ${p?.current_tier ?? 1}`} />
      <Stat label="Pre-test" value={p?.pretest_completed_at ? 'Complete' : 'Required'} />
      <Stat label="Tutorial" value={p?.tutorial_completed_at ? 'Complete' : 'Required'} />
    </section>
    <section className="card"><div className="section-head"><div><h2>Scenario progression</h2><p className="muted">Tier 1 is available first. Higher tiers remain configurable by the project team.</p></div></div>
      <div className="tier-grid">{[1,2,3].map(tier => <div className={`tier ${p?.current_tier >= tier ? 'unlocked' : ''}`} key={tier}><div><span className="eyebrow">TIER {tier}</span><h3>{['Basic','Intermediate','Advanced'][tier-1]}</h3></div><span className="lock">{p?.current_tier >= tier ? 'Unlocked' : `🔒 ${thresholds[tier]} XP`}</span></div>)}</div>
    </section>
    <section className="card"><div className="section-head"><div><h2>Available scenarios</h2><p className="muted">Scenario content is database-driven; ESI classification is never generated by AI.</p></div></div>
      {scenarios.length ? <div className="scenario-list">{scenarios.map(s => <Link className="scenario-row" to={`/scenarios/${s.id}`} key={s.id}><span><b>{s.title}</b><small>Tier {s.tier} · {s.time_limit}s · {s.max_xp} XP</small></span><span>Start →</span></Link>)}</div> : <div className="empty">No approved scenarios are available yet.</div>}
    </section>
    {data?.recent_results?.length > 0 && <section className="card"><h2>Recent results</h2><div className="scenario-list">{data.recent_results.map(r => <div className="scenario-row" key={r.id}><span><b>{r.title}</b><small>{r.status} · {r.accuracy}% · {r.xp_earned} XP</small></span><span>{r.performance_rating || 'In progress'}</span></div>)}</div></section>}
  </main>;
}

function Stat({ label, value }) { return <div className="card stat"><span className="muted">{label}</span><strong>{value}</strong></div>; }
function FacultyPlaceholder() { return <main className="app-shell"><header className="topbar"><div className="brand">TRIAGE<span>LEARN</span></div></header><section className="hero"><p className="eyebrow">FACULTY</p><h1>Faculty monitoring</h1><p className="muted">The Week 1 foundation protects faculty routes. Read-only analytics are scheduled for Week 4.</p></section></main>; }
